import { spawnSync } from 'node:child_process';
import fs from 'node:fs';
import path from 'node:path';

const root = path.resolve(import.meta.dirname, '..');
const deploymentFile = path.join(root, '.gas-deployment.json');
const generatedUrlFile = path.join(root, 'src/gas-backend-url.generated.ts');
const deployDescription = 'Lineup planner API';

function run(command, args, { capture = false, allowFailure = false } = {}) {
  const result = spawnSync(command, args, {
    cwd: root,
    encoding: 'utf8',
    stdio: capture ? ['inherit', 'pipe', 'pipe'] : 'inherit',
  });

  if (result.status !== 0 && !allowFailure) {
    if (capture) {
      if (result.stdout) process.stdout.write(result.stdout);
      if (result.stderr) process.stderr.write(result.stderr);
    }
    process.exit(result.status ?? 1);
  }

  return result;
}

function claspOutput(result) {
  return `${result.stdout ?? ''}${result.stderr ?? ''}`;
}

function runClasp(args, options = {}) {
  return run('npx', ['clasp', ...args], options);
}

function readStoredDeployment() {
  if (!fs.existsSync(deploymentFile)) return null;

  try {
    const parsed = JSON.parse(fs.readFileSync(deploymentFile, 'utf8'));
    return typeof parsed.deploymentId === 'string' ? parsed.deploymentId : null;
  } catch {
    return null;
  }
}

function listDeployments() {
  const result = runClasp(['deployments'], { capture: true, allowFailure: true });
  const output = claspOutput(result);
  if (result.stdout) process.stdout.write(result.stdout);
  if (result.stderr) process.stderr.write(result.stderr);

  const deployments = [];
  for (const line of output.split('\n')) {
    const match = line.match(/^- ([^\s]+) @(HEAD|\d+)(?: - (.+))?$/);
    if (!match) continue;
    deployments.push({
      deploymentId: match[1],
      version: match[2],
      description: match[3]?.trim() ?? '',
    });
  }

  return deployments;
}

function chooseDeploymentId(storedId, deployments) {
  if (storedId && deployments.some((entry) => entry.deploymentId === storedId)) {
    return storedId;
  }

  const byDescription = deployments.find((entry) => entry.description === deployDescription);
  return byDescription?.deploymentId ?? null;
}

function isMissingDeploymentError(output) {
  return /requested entity was not found|404|deployment.*not found/i.test(output);
}

function parseDeploymentId(output) {
  const match = output.match(/^- ([^\s]+) @(\d+)\.$/m);
  if (!match) return null;
  return { deploymentId: match[1], versionNumber: match[2] };
}

function writeBackendUrl(deploymentId) {
  const backendUrl = `https://script.google.com/macros/s/${deploymentId}/exec`;

  fs.writeFileSync(
    deploymentFile,
    `${JSON.stringify({ deploymentId, backendUrl }, null, 2)}\n`,
  );

  fs.writeFileSync(
    generatedUrlFile,
    `/** Generated by npm run gas:deploy — do not edit by hand. */\nexport const gasBackendUrl = '${backendUrl}';\n`,
  );

  return backendUrl;
}

function deployWithClasp(deploymentId) {
  const args = ['deploy', '--description', deployDescription];
  if (deploymentId) args.push('--deploymentId', deploymentId);

  const result = runClasp(args, { capture: true, allowFailure: true });
  const output = claspOutput(result);
  if (result.stdout) process.stdout.write(result.stdout);
  if (result.stderr) process.stderr.write(result.stderr);

  return { result, output };
}

console.log('Building and pushing Apps Script…');
run('npm', ['run', 'gas:push']);

const storedDeploymentId = readStoredDeployment();
const deployments = listDeployments();
let deploymentId = chooseDeploymentId(storedDeploymentId, deployments);

if (deploymentId) {
  console.log(`Redeploying ${deploymentId}…`);
} else if (storedDeploymentId) {
  console.log(`Stored deployment ${storedDeploymentId} was not found; creating a new one…`);
} else {
  console.log('Creating new deployment…');
}

let { result, output } = deployWithClasp(deploymentId);

if (result.status !== 0 && deploymentId && isMissingDeploymentError(output)) {
  console.warn('Deployment update failed; creating a new deployment instead…');
  ({ result, output } = deployWithClasp(null));
}

if (result.status !== 0) {
  process.exit(result.status ?? 1);
}

const parsed = parseDeploymentId(output);
if (!parsed) {
  console.error('Could not parse deployment ID from clasp output.');
  process.exit(1);
}

const backendUrl = writeBackendUrl(parsed.deploymentId);

console.log(`Updated ${path.relative(root, generatedUrlFile)}`);
console.log(`Backend URL: ${backendUrl}`);
