import { spawnSync } from 'node:child_process';
import fs from 'node:fs';
import path from 'node:path';

const root = path.resolve(import.meta.dirname, '..');
const deploymentFile = path.join(root, '.gas-deployment.json');
const generatedUrlFile = path.join(root, 'src/gas-backend-url.generated.ts');
const deployDescription = 'Lineup planner API';

function run(command, args, { capture = false } = {}) {
  const result = spawnSync(command, args, {
    cwd: root,
    encoding: 'utf8',
    stdio: capture ? ['inherit', 'pipe', 'pipe'] : 'inherit',
  });

  if (result.status !== 0) {
    if (capture) {
      if (result.stdout) process.stdout.write(result.stdout);
      if (result.stderr) process.stderr.write(result.stderr);
    }
    process.exit(result.status ?? 1);
  }

  return result;
}

function readStoredDeployment() {
  if (!fs.existsSync(deploymentFile)) return null;

  try {
    const parsed = JSON.parse(fs.readFileSync(deploymentFile, 'utf8'));
    return typeof parsed.deploymentId === 'string' ? parsed.deploymentId : null;
  } catch {
    return null;
  }
}

function parseDeploymentId(output) {
  const match = output.match(/^- ([^\s]+) @(\d+)\.$/m);
  if (!match) return null;
  return { deploymentId: match[1], versionNumber: match[2] };
}

function writeBackendUrl(deploymentId) {
  const backendUrl = `https://script.google.com/macros/s/${deploymentId}/exec`;

  fs.writeFileSync(
    deploymentFile,
    `${JSON.stringify({ deploymentId, backendUrl }, null, 2)}\n`,
  );

  fs.writeFileSync(
    generatedUrlFile,
    `/** Generated by npm run gas:deploy — do not edit by hand. */\nexport const gasBackendUrl = '${backendUrl}';\n`,
  );

  return backendUrl;
}

console.log('Building and pushing Apps Script…');
run('npm', ['run', 'gas:push']);

const storedDeploymentId = readStoredDeployment();
const deployArgs = ['clasp', 'deploy', '--description', deployDescription];
if (storedDeploymentId) {
  deployArgs.push('--deploymentId', storedDeploymentId);
  console.log(`Redeploying ${storedDeploymentId}…`);
} else {
  console.log('Creating new deployment…');
}

const deployResult = run('npx', deployArgs, { capture: true });
const deployOutput = `${deployResult.stdout ?? ''}${deployResult.stderr ?? ''}`;
if (deployResult.stdout) process.stdout.write(deployResult.stdout);
if (deployResult.stderr) process.stderr.write(deployResult.stderr);

const parsed = parseDeploymentId(deployOutput);
if (!parsed) {
  console.error('Could not parse deployment ID from clasp output.');
  process.exit(1);
}

const backendUrl = writeBackendUrl(parsed.deploymentId);

console.log(`Updated ${path.relative(root, generatedUrlFile)}`);
console.log(`Backend URL: ${backendUrl}`);
