/** Generated by npm run gas:deploy — do not edit by hand. */
export const gasBackendUrl =
  'https://script.google.com/macros/s/AKfycbxmGd0_jjD1znuizGRf-rbAqyAOTDobxbzURac4e-962J3WOyROaATc4qWYe7onsLfG6Q/exec';
