/** Generated by npm run gas:deploy — do not edit by hand. */
export const gasBackendUrl = 'https://script.google.com/macros/s/AKfycbzU-1JENqwkKNvNC_fEDke4Yepao7GO513bhD9JxQDNfcBVlYwnBWFoBhzTBKeNmkhdxw/exec';
